/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <GPIO_Driver.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void);

void delay()
{
	for(int i=0; i < 1000000; i++ ); //will generate some delay
}


int main(void)
{

//	case:1 GPIO INITIALIZE AND DE INITIALIZE
//	GPIO_ClockControl(GPIOA, ENABLE);
//	/*
//	 * GPIOA
//	 * GPIO_PIN 0
//	 * GPIO_MODE OUTPUT
//	 * GPIO_SPEED HIGH SPEED
//	 * GPIO_PU/D PU
//	 * GPIO_PUSHPULL
//	 * GPIO_AF1
//	 */
//	GPIO_Init(GPIOA, GPIO_PIN_0, GPIO_OUTPUT, GPIO_HIGH_SPEED, GPIO_PU, GPIO_PUSHPULL, GPIO_AF1);
//	GPIO_DeInit(GPIOA);
//    /* Loop forever */
//	for(;;);

////CASE:2 : blinking the 4 leds connected to gpiod port with some delay
//
//	// ENABLING THE GPIOD CLOCK CONTROL
//	GPIO_ClockControl(GPIOA, ENABLE);
//
//	while(1){
//	//SET THE PORT PINS
//	GPIO_Init(GPIOD, GPIO_PIN_12, GPIO_OUTPUT, GPIO_HIGH_SPEED, GPIO_NOPUPD, GPIO_PUSHPULL, GPIO_AF1);
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_12, ENABLE);
//	delay();
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_12, DISABLE);
//
//	GPIO_Init(GPIOD, GPIO_PIN_13, GPIO_OUTPUT, GPIO_HIGH_SPEED, GPIO_NOPUPD, GPIO_PUSHPULL, GPIO_AF1);
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_13, ENABLE);
//	delay();
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_13, DISABLE);
//
//	GPIO_Init(GPIOD, GPIO_PIN_14, GPIO_OUTPUT, GPIO_HIGH_SPEED, GPIO_NOPUPD, GPIO_PUSHPULL, GPIO_AF1);
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_14, ENABLE);
//	delay();
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_14, DISABLE);
//
//	GPIO_Init(GPIOD, GPIO_PIN_15, GPIO_OUTPUT, GPIO_HIGH_SPEED, GPIO_NOPUPD, GPIO_PUSHPULL, GPIO_AF1);
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_15, ENABLE);
//	delay();
//	GPIO_WriteToOut_Pin(GPIOD, GPIO_PIN_15, DISABLE);
//
//	GPIO_ToggleOut_Pin(GPIOD,GPIO_PIN_15);		// toggling the led
//	delay();
//	}
//
//// case 2: ended

//CASE:3 : WRITE A PROGRAM TO TOGGLE THE LED WHEN BUTTON PRESSED
	// button is  connected to PA0 when you press the button will give high signal when u release the button will provide low signal
// configuring button details PA0

	GPIO_ClockControl(GPIOA, ENABLE);
	GPIO_Init(GPIOA, GPIO_PIN_0, GPIO_INPUT, GPIO_HIGH_SPEED, GPIO_NOPUPD, GPIO_PUSHPULL, GPIO_AF1);
// CONFIGURING THE LED12
	GPIO_ClockControl(GPIOD, ENABLE);
	GPIO_Init(GPIOD, GPIO_PIN_12, GPIO_OUTPUT, GPIO_HIGH_SPEED, GPIO_NOPUPD, GPIO_PUSHPULL, GPIO_AF1);

	while(1)
	{
		if(GPIO_ReadFromIn_Pin(GPIOA, GPIO_PIN_0))
		{
			delay();
			GPIO_ToggleOut_Pin(GPIOD,GPIO_PIN_12);
		}
	}








}
